language: node_js
os:
  - linux
node_js:
  - "12"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
install:
  - npm i -g codecov
  - yarn install
  - yarn run test:ci
  - codecov
